### ISSUE TITLE
Could you please provide the codes of other models in the paper

### ISSUE THREAD

**Issue by WangZhi-wz** [zijinY/DCRNet#1]
Could you please provide the codes of other models in the paper? I think your model is very helpful, so I would like to discuss the codes of other comparative models in the paper. Could you please provide it？
Thanks！

**Comment by zijinY** [comment]
Thank you for your attention to our work~
I delivered results of other comparative methods(PraNet, ACSNet, et.al) using their offered codes. What problems did you encounter when you implement the codes of other comparative models?
