### ISSUE TITLE
About pretrained model on Kvasir dataset

### ISSUE THREAD

**Issue by Sunxy11** [zijinY/DCRNet#2]
I wonder if you could release the pretrained model on Kvasir dataset in your paper. I can't reproduce the experimental results in your paper. I don't know if there is a mistake in the middle.

**Comment by zijinY** [comment]
ResNet-34 pretrained model is used as bakcbone, and trained model weight on Kvasir dataset is released in https://drive.google.com/file/d/1tmd8hYSLuCbDlC-jAjQufI39SACroWe3/view?usp=share_link. Good regards.
